dist: trusty
language: node_js
node_js:
  - "9"
dist: trusty
sudo: required
before_script:
  - npm install -g @angular/cli
script:
  - ng lint
  - npm run build:lib
before_deploy:
  - cd lib-dist
addons:
  sonarcloud:
    organization: "satrec-initiative"
    token:
      secure: "d44bec831c9cbcebff79904b46a5bf5f543b2178"
deploy:
  provider: npm
  email: satreci-gsd@satreci.com
  skip_cleanup: true
  api_key: $NPM_TOKEN
  on:
    branch: master
