dist: trusty
language: node_js
node_js:
  - "9"
dist: trusty
sudo: required
before_script:
  - npm install -g @angular/cli
script:
  - ng lint
  - npm run build:lib
  - npm run publish:lib
before_deploy:
  - cd lib-dist
deploy:
  provider: npm
  email: satreci-gsd@satreci.com
  skip_cleanup: true
  api_key: $NPM_TOKEN
  on:
    branch: master
