dist: trusty
language: node_js
node_js:
  - "9"
dist: trusty
sudo: required
before_script:
  - npm install -g @angular/cli
addons:
  sonarcloud:
    organization: "satrec-initiative"
    token:
      secure: "3dc3d95cef2f55abb09ecbcd51a9a64f3cc3522c"
script:
  - ng lint
  - sonar-scanner
  - npm run build:lib
before_deploy:
  - cd lib-dist
deploy:
  provider: npm
  email: satreci-gsd@satreci.com
  skip_cleanup: true
  api_key: $NPM_TOKEN
  on:
    branch: master
